### ISSUE TITLE
Huge build time with platformio caused by introduction of the ESP-IDF example

### ISSUE THREAD

**Issue by mathieucarbou** [bertmelis/espMqttClient#145]
The introduction of the latest comit (885e631f1669aaaeb88098811aace215a43d01b8) causes a huge build time on platformio because it is going through the example to also download their dependencies which includes the whole platform. That is a Gb of download.

![image](https://github.com/bertmelis/espMqttClient/assets/61346/23c68a37-28b2-4b85-bb5b-8d6bff50c5aa)

Using:

```
lib_compat_mode = strict
lib_ldf_mode = deep+
```

**Comment by bertmelis** [comment]
You're talking about CI or are you just using the library?

**Comment by mathieucarbou** [comment]
> You're talking about CI or are you just using the library?

Just pointing to the library (master branch) in platfeformio causes this huge download since the esp-idf sample is there.

**Comment by bertmelis** [comment]
So the 'build time' is actually download time. Nonetheless it obviously is unnecessary and highly undesirable. Not sure how to solve though. I'm looking into this!

**Comment by mathieucarbou** [comment]
> So the 'build time' is actually download time. Nonetheless it obviously is unnecessary and highly undesirable. Not sure how to solve though. I'm looking into this!
> 
> Question: how did you install the library?

Yes, git download time. But the arduino project is huge. Even on an optical fiber connection it takes time.

I am pointing to: `https://github.com/bertmelis/espMqttClient` (there is no release yet containing this example).

One other way to solve that would be to add a section like that in library.json to limit what gets exported:

``
  "export": {
    "include": [
      "examples",
      "src",
      "library.json",
      "library.properties",
      "LICENSE",
      "README.md"
    ]`
``

this would only solve it for releases but not solve it for someone pointing directly to a branch or tag in the git repo.

**Comment by bertmelis** [comment]
As a **workaround**, you can point to the zip file from the main branch instead of the git link.

**Comment by bertmelis** [comment]
I'll just remove the esp-idf CI workflow and with that also the submodules.
