### ISSUE TITLE
[BUG] ESP32 with espMqttClient crashes with heavily Network traffic

### ISSUE THREAD

**Issue by knickohr** [bertmelis/espMqttClient#153]
Which platform, esp8266 or **esp32**?
Do you use TLS or not? No
Do you use an IDE (Arduino, **Platformio**...)?
Which version of the Arduino framework? Latest

Please include any debug output and/or decoded stack trace if applicable.

We using this lib with AhoyDTU. Ahoy has a lot of single topics. In my case with 16 inverters over 1000. so far so good, but if I have much other network traffic the ESP crashes if MQTT is enabled. Nothing happens without other network activity except MQTT.

I can reproduce this every time. Publish a lot of sigle topics in a short time. Make parallel heavy network traffic, maybe downloading or moving really big files. Broker (local mosquitto on a raspi) disconnects and bäm 💥 reboot of the ESP.

If I do this without MQTT, nothing happens too, no reboot.

**Comment by knickohr** [comment]
The Complete Code is here :

https://github.com/lumapu/ahoy/tree/development03/src

Use the dev branch, not the main. Main is way ahead the dev, but still dev 😉

Sorry, I don’t have crashlog.

**Comment by bertmelis** [comment]
Would it be possible to have a crashlog? I don't even know where to start looking for a bug.

**Comment by knickohr** [comment]
[message-3 2.txt](https://github.com/bertmelis/espMqttClient/files/15439297/message-3.2.txt)

**Comment by bertmelis** [comment]
`StoreProhibitedCause` means your writing to memory that is not available
`Crashed task handle: 0x3ffbd4d4`: I don't know which task that is. It's not the MQTT task nor the Arduino setup/loop task.

This isn't going to be an easy search...

**Comment by bertmelis** [comment]
Is it possible to test the code in the PR?

**Comment by knickohr** [comment]
Merged & testing 👍

**Comment by knickohr** [comment]
Works great for my Setup. Uptime 40 hours and running 👍

🙇

Thx a lot 😎

**Comment by bertmelis** [comment]
I'll do some more testing on my site (async) and merge/release soon.
