### ISSUE TITLE
[BUG] Connection done twice

### ISSUE THREAD

**Issue by GMagician** [bertmelis/espMqttClient#161]
I made a soft that should work both on ESP8266 and ESP32 usign this library.
With ESP8266 works has expected while on ESP32 I see, on broker side, that sometime the connections open 2 sockets (port is one next to other).

TLS (with ESP32 with some problems with certificates)
PlatformIO

Broker log:
1725571310: New connection from 192.168.?2?.?1?:59508 on port 8883.
1725571310: New connection from 192.168.?2?.?1?:59509 on port 8883.
1725571310: OpenSSL Error[0]: error:0A000126:SSL routines::unexpected eof while reading
1725571310: Client <unknown> disconnected: Protocol error.

**Comment by bertmelis** [comment]
Can you share the code you use to make the connection?

**Comment by GMagician** [comment]
Sure, here it is.
To test it I added a seril print in `connectToMqtt()` function and it's called once.

```C++
String availableTopic;
char localHostname[sizeof(BASEHOSTNAME)+6];
bool timeSet;
espMqttClientSecure mqttClient;
Ticker mqttReconnectTimer;


void fatalError(uint8_t code)
  {
  while (true)
    {
    for (uint8_t i = 0; i < code; i++)
      {
      hal.setLed(true);
      delay(250);
      hal.setLed(false);
      delay(500);
      hal.wdtReset();
      }
    delay(1000);
    }
  }

void connectToWiFi()
  {
  ESP_LOGI(MC_TAG, "Connecting to Wi-Fi...\n");

  WiFiManager wifiManager;
  #if !defined(DEBUG)
    wifiManager.setDebugOutput(false);
  #endif
  if (wifiManager.autoConnect(localHostname))
    return;

  ESP_LOGE(MC_TAG, "Failed to connect and hit timeout");
  }

void connectToMqtt()
  {
  ESP_LOGI(MC_TAG, "Connecting to MQTT...\n");
  IPAddress remote_addr;
  if (WiFi.hostByName(SERVER_LOCAL, remote_addr))
    mqttClient.setServer(remote_addr, MQTT_PORT);
  else
    {
    ESP_LOGE(MC_TAG, "host not found...\n");
    fatalError(4);
    }
  mqttClient.connect();
  }

void timeIsSet()
  {
  if (!timeSet)
    {
    timeSet = true;
    #ifdef DEBUG
      time_t currentTime = time(nullptr);
      struct tm * tma = localtime(&currentTime);
      ESP_LOGI(MC_TAG, "Synchronized time: %02d/%02d/%4d %02d:%02d:%02d\n", tma->tm_mday, (1 + tma->tm_mon), (1900 + tma->tm_year), tma->tm_hour, tma->tm_min, tma->tm_sec);
    #endif
    connectToMqtt();
    }
  }

void onWiFiConnect()
  {
  ESP_LOGI(MC_TAG, "Connected to Wi-Fi.\n");
  if (!MDNS.begin(localHostname))
    ESP_LOGE(MC_TAG, "mDNS failed.\n");
  if (timeSet)
    connectToMqtt();
  }

void onWiFiDisconnect()
  {
  mqttReconnectTimer.detach();  // Ensure we don't reconnect to MQTT while reconnecting to Wi-Fi
  ESP_LOGI(MC_TAG, "Disconnected from Wi-Fi.\n");
  }

void onMqttConnect(bool sessionPresent)
  {
  ESP_LOGI(MC_TAG, "Connected to MQTT.\n");
  ESP_LOGI(MC_TAG, "Session present: %d\n", sessionPresent);
  mqttClient.publish(availableTopic.c_str(), 0, true, "online");
  }

void onMqttDisconnect(espMqttClientTypes::DisconnectReason reason)
  {
  ESP_LOGI(MC_TAG, "Disconnected from MQTT: %u.\n", static_cast<uint8_t>(reason));

  if (WiFi.isConnected())
    mqttReconnectTimer.once(5, connectToMqtt);
  }

void onMqttSubscribe(uint16_t packetId, const espMqttClientTypes::SubscribeReturncode* codes, size_t len) {
  ESP_LOGI(MC_TAG, "Subscribe acknowledged.\n  packetId: %u\n", packetId);
  for (size_t i = 0; i < len; i++)
    ESP_LOGI(MC_TAG, "  qos: %d\n", static_cast<uint8_t>(codes[i]));
  }

void onMqttMessage(const espMqttClientTypes::MessageProperties& properties, const char* topic, const uint8_t* payload, size_t len, size_t index, size_t total)
  {
  ESP_LOGI(MC_TAG, "Publish received.\n");
  ESP_LOGI(MC_TAG, "  topic: %s\n", topic);
  ESP_LOGI(MC_TAG, "  qos: %d\n", properties.qos);
  ESP_LOGI(MC_TAG, "  dup: %d\n", properties.dup);
  ESP_LOGI(MC_TAG, "  retain: %d\n", properties.retain);
  ESP_LOGI(MC_TAG, "  len: %u\n", len);
  ESP_LOGI(MC_TAG, "  index: %u\n", index);
  ESP_LOGI(MC_TAG, "  total: %u\n", total);
  }

void setup() 
  {
  Serial.begin(115200);

  snprintf(localHostname, sizeof(localHostname), "%s%06X", BASEHOSTNAME, hal.getUID());
  availableTopic = "AAB" + String("/available");

  hal.onTimeSet(timeIsSet);
  hal.configTimeZone(TZ_XXXX, SERVER_LOCAL);

  WiFi.setAutoConnect(false);
  WiFi.setAutoReconnect(true);
  hal.onStationModeGotIP(onWiFiConnect);
  hal.onStationModeDisconnected(onWiFiDisconnect);

  mqttClient.onConnect(onMqttConnect);
  mqttClient.onDisconnect(onMqttDisconnect);
  mqttClient.onSubscribe(onMqttSubscribe);
  mqttClient.onMessage(onMqttMessage);

  mqttClient.setKeepAlive(5);
  mqttClient.setClientId(localHostname);
  mqttClient.setCredentials(MQTT_USER, MQTT_PASSWORD);
  #if defined(ESP8266)
    mqttClient.setTrustAnchors(new X509List(rootCACertificate));
    mqttClient.setClientRSACert(new X509List(certificate), new PrivateKey(privateKey));
  #elif defined(ESP32)
    mqttClient.setCACert(rootCACertificate);
    //mqttClient.setCertificate(certificate);
    //mqttClient.setPrivateKey(privateKey);
  #endif
  mqttClient.setWill(availableTopic.c_str(), 1, true, "offline");

  connectToWiFi();
  }

void loop()
  {
  #if defined(ESP8266)
    MDNS.update();
  #endif
  mqttClient.loop();
  }
```

**Comment by bertmelis** [comment]
You call `connectToMqtt` both in `onWiFiConnect` and `timeIsSet`. I assume both will be called almost at the same time: when WiFi is connected (actually the callback is fired when you get your IP, so when DHCP does its job), time is also set by DHCP.

This is undesirable. The lib should be able to handle this but this is not 100% guaranteed.

The easy workaround is to remove the `timeIsSet` callback and rely solely on the WiFi callback. I will look into strengthening the concurrency handling code.

**Comment by GMagician** [comment]
Theoretically no. I added a parameter to 'connectToMqtt' and printed value to serial. Just 1 call is done.
timeIsTime should be called after NPT server set the timer, and it shoult take a bit to do it (I usually see time sync message after a while)
It's also true that serial seems not to me reliable.

**Comment by GMagician** [comment]
side note: timeIsSet is mandatory because SSL can't validate certificate if time is not valid (this is why a postpone mqtt connection)

**Comment by bertmelis** [comment]
That is really strange. Can you enable debugging output for teh MQTT lib and share the output?

This will probably one stupid and tiny mistake somewhere but until we see it, it is a huge flaw.

Which version of the Arduino framework you are using?

**Comment by GMagician** [comment]
> This will probably one stupid and tiny mistake somewhere but until we see it, it is a huge flaw.

I agree, usual stupid thing that you call this way when you find them, but until then a pain in ....

> Which version of the Arduino framework you are using?

PlatformIO latest

**Comment by GMagician** [comment]
Not able to see log messages, but this is a problem I have with log_x functions.
I added -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
             -D DEBUG_ESP_MQTT_CLIENT
to build_flags, code compile down to `int log_printfv(const char *format, va_list arg)` but serial diusplay nothing

**Comment by GMagician** [comment]
I really think I have a defective board. Too many issues and not constant.
In Order:
1) serial something stop to send messages
2) windows sometime give me an error on usb port
3) loop sometime hangs with nothing sent on monitor (loop code blinks the led and it stops for a long time)
4) ssl sometime fails with 'alert on certificate', sometime with 'unexpected eof while reading' or even 'length mismatch'
5) log_e functions almost never work (just 2 time I had been able to see log...same compile/linker options as now)
6) double socket open (this issue)
7) Sometime my log code prints "mqtt connecting" "mqtt disconnected" but broker didn't see any connection
all with same code loaded in scattered order.

and to close all, the same code with same libraries with es8266 works with no issues

**Comment by bertmelis** [comment]
Might be flashing memory issues. Check flash type, lower upload speed, checksum verification...

As always: don't hesitate to open an issue. You're not only helping yourself but potentially many others.
