### ISSUE TITLE
[BUG] wifi not connecting automatically !!

### ISSUE THREAD

**Issue by ajen2420** [bertmelis/espMqttClient#163]
platform - esp32?
Do you use TLS or not - yes (SSL) by root certificate
Do you use an IDE (Arduino, Platformio...) - arduino IDE - esp32 core 3.xx

Wifi not automatically connecting after leave disconnect several hour. I also add wifi.reconnect function which run every 30 second if wifi not connected.

**Comment by bertmelis** [comment]
If you have a problem with WiFi, you should open an issue in the Arduino repo. There not much I can do here.

**Comment by ajen2420** [comment]
Actually I was using pubsub client where wifi worked fine. Even after several days later I turn on my Hotspot, it reconnect automatically.
but after I added your espmqttclient library in my code, wifi not automatically connecting after 8 to 9 hour without wifi. For a short periods disconnection, it connecting fine. So definitely it is not wifi issue.

**Comment by ajen2420** [comment]
hi , i just ran a serial monitor to check free heap memory available, but what what I found is that free heap memory reducing continuously until zero free heap memory while wifi disconnected. then it crashes... please solve this issue.

**Comment by ajen2420** [comment]
i fix the problem. Besically it was saving mqtt packets in heap memory while it was offline. this is why heap memory got full. I fix this by providing a condition so that it only publish while it is connected to MQTT server.

**Comment by bertmelis** [comment]
that would be my guess too.

You have two other options:
- use the built-in memory pool so the memory is limited to that pool: https://github.com/bertmelis/espMqttClient/blob/main/src/Config.h#L65
- define a bigger free heap limit for allocating packets: https://github.com/bertmelis/espMqttClient/blob/main/src/Config.h#L32
