### ISSUE TITLE
Payload length being smaller then sent

### ISSUE THREAD

**Issue by ACil32** [bertmelis/espMqttClient#168]
So i sent a payload with a size around 5000 bytes when when i printed that length in a subscriber esp32 it showed the length being around 1400 or 700 bytes. this is the same issue i had with asyncmqttclient and in a couple of the issues this library was stated to have fixed this, yet the same still happens. is there something i need to do first in order to send payloads that size?

**Comment by bertmelis** [comment]
You can also find a code sample in the documentation: https://www.emelis.net/espMqttClient/#code-samples

**Comment by bertmelis** [comment]
Chunked sending is only needed when the message is too big to fit in memory.

Receiving large packets will always be chunked as this depends on TCP (MTU actually) and is probably about 1500 bytes.

**Comment by ACil32** [comment]
alright so it works but its basically the same as pubsubclient to me now with its speed. after using it it became really slow.

**Comment by bertmelis** [comment]
The underlying TCP library is probably the same. You can tinker with tasks and priority but the ESP32, although very capable, is still a microcontroller with its limitations.

This library isn't faster than pubsubclient but it has more features.

**Comment by ACil32** [comment]
Yea I see that, it's also more updated so I will definitely continue using it over others for other projects, but I'll probably have to find a different solution to this issue. Thanks a lot though 🙏

**Comment by bertmelis** [comment]
Good luck finding a solution!
