### ISSUE TITLE
[BUG] setKeepAlive not working

### ISSUE THREAD

**Issue by Pablo2048** [bertmelis/espMqttClient#17]
Hi Bert,
thank You for this new library. I'm trying to switch from asyncmqtt to this one mainly because of SSL and I found strange behavior - when I use `  mqttClient.setKeepAlive(120);` the library wont connect to the server. I've used Your `simple-esp32.ino` example, added credentials and KeepAlive
![Snímek z 2022-07-22 09-44-20](https://user-images.githubusercontent.com/6281647/180389910-c457d355-a9e8-44d1-9f34-d9e82e49ec6c.png)
Unfortunately the result is
![Snímek z 2022-07-22 09-45-16](https://user-images.githubusercontent.com/6281647/180390039-35beacd1-255a-4665-8a1a-e4c31b9ffbfb.png)
If I remove `mqttClient.setKeepAlive(120);` everything is working as expected. Can You please take a look or suggest, what I did wrong?
Thanks.
Eh: I'm using v1.1.0 version of the library.

**Comment by bertmelis** [comment]
Could you check the disconnect reason? (Printf as uint8_t)

**Comment by Pablo2048** [comment]
Yes - reason = 2 MQTT_IDENTIFIER_REJECTED.

**Comment by Pablo2048** [comment]
The only thing I did is add two lines `setCredentials` and `setKeepAlive` to the example given (and add MQTT_USER and MQTT_PASS defines).
![Snímek z 2022-07-22 10-45-03](https://user-images.githubusercontent.com/6281647/180401289-17840da0-418c-41c5-91c6-e81e853864a3.png)
I'm using Lilygo Blynk_V1 board with SIM800 GSM (now using only the wifi) and Wrover module. Arduino Core for PIO is version 4.0.0 because of lack of PPP support in latter versions.
![lilygo](https://user-images.githubusercontent.com/6281647/180401819-66bd1365-2ebe-4e82-b7b2-503177342494.jpeg)

**Comment by Pablo2048** [comment]
Right now I did same test with PIO Core 5.0.0 - no change - still disconnected with reason 2. I've tried to print out the ClientID adding this:
![Snímek z 2022-07-22 10-54-12](https://user-images.githubusercontent.com/6281647/180402940-c38b2df7-0c56-4e2d-8a79-f3c0cd4f5ea3.png)
Unfortunately the compilation ends with this error:
![Snímek z 2022-07-22 10-55-35](https://user-images.githubusercontent.com/6281647/180403092-9f867d19-60c5-4d5f-8b58-7031a156ec8c.png)

**Comment by bertmelis** [comment]
When changing from 1.0.1 to 1.1.0, I changed the conditional code to check for `ARDUINO_ARCH_ESP32` instead of `ESP32`. Maybe this results in no code at all for your board, leaving the clientId empty which is a special case.

Did I forget to define `getClientId()`? OMG.

**Comment by Pablo2048** [comment]
Now I get the version 1.0.1 - same result (disconnect reason = 2). Then I've get back with version 1.1.0, manually added Your patch for getclientid and got this:
![Snímek z 2022-07-22 11-06-50](https://user-images.githubusercontent.com/6281647/180405452-6851d896-aa0a-4487-b56c-326e039281a2.png)

**Comment by bertmelis** [comment]
What happens if you set a clientID? For example, the same but without the dash: esp123445.

It's still strange why it would not connect when keepalive is set. Underlying there is no difference.

**Comment by Pablo2048** [comment]
The reason has changed to 0:
![Snímek z 2022-07-22 11-16-55](https://user-images.githubusercontent.com/6281647/180407363-c40da7a3-da2b-4420-8fd3-df4ce79594f3.png)

**Comment by Pablo2048** [comment]
Well - wait a moment :-( I have MQTT broker internet down right now...

**Comment by bertmelis** [comment]
allright, we're getting somewhere.

**Comment by Pablo2048** [comment]
So I've switched to Mosquitto public broker @ test.mosquitto.org and everything seems to be working flawlessly. It seems like problem with my own Mosquitto configuration - Sorry for bothering You. I'm closing this as my error.

**Comment by bertmelis** [comment]
Thank you for testing. Because of your test a bug was revealed.

I'll merge and publish a bugfix version.

**Comment by Pablo2048** [comment]
So the explanation is that my Mosquitto broker configuration has set the `max_keepalive` value to 60 seconds. According to this documentation from Mosquitto (https://mosquitto.org/man/mosquitto-conf-5.html):
![Snímek z 2022-07-22 13-27-12](https://user-images.githubusercontent.com/6281647/180430089-a8556c18-1ceb-4444-acb3-fdcb868e4701.png)
the broker rejects client with `identifier rejected` error code. The error was definitely on my side in the broker configuration.. Bert thanks again for the library and for Your support...
