### ISSUE TITLE
[BUG] _checkPing(): Disconnecting, server exceeded keepalive

### ISSUE THREAD

**Issue by kirwinrMK** [bertmelis/espMqttClient#19]
#### Do not use to discuss topics! 

**Describe the bug**
When sending data every 5 seconds in loop, I receive the error "_checkPing(): Disconnecting, server exceeded keepalive"
If not sending constant data it does not disconnect. 

Which platform, esp8266 or esp32?
esp32 sparkfun thingplus
Do you use TLS or not?
No tls
Do you use an IDE (Arduino, Platformio...)?
PlatformIO
Which version of the Arduino framework?
5.1.0

Please include any debug output and/or decoded stack trace if applicable.

14:56:27.318 > [ 26916][I][MqttClient.cpp:289] _checkOutgoing(): tx 120/120

14:56:32.213 > [ 31811][W][MqttClient.cpp:374] _checkPing(): Disconnecting, server exceeded keepalive

14:56:32.218 > [ 31816][I][MqttClient.cpp:601] _clearQueue(): clearing queue (clear session: false)

**Expected behaviour**
It shouldn't disconnect

**To Reproduce**
Steps to reproduce the behaviour:

**Example code**
```cpp
// Put code here to reproduce the bug, if possible
```

**Additional context**

**Comment by kirwinrMK** [comment]
Some more info:
The Arduino loop is nonblocking and it works for 30 seconds. 
This leads me to believe `_state = State::connectingMqtt;` is not being called

**Comment by kirwinrMK** [comment]
Okay after digging further, it seems that `_lastClientActivity` is being reset even when sending QOS = 0 packets. 
QOS 0 packets do not require a response from the broker. 
Either `_lastClientActivity` should not be reset when sending QOS 0 messages or disconnect due to server inactivity needs changed.

**Comment by bertmelis** [comment]
You're right, good catch.

I'm not at my computer now so I can't dig deep into the code.  I think the cleanest solution would be to send a ping when clientActivity is due oOR when serverActivity is due. The latter isn't implemented so it inst triggered when no response has been expected.

I'm happy to accept a PR or I'll fix it tomorrow (It's midnight in Europe now)

**Comment by bertmelis** [comment]
So, change this line:
https://github.com/bertmelis/espMqttClient/blob/94d6f091d137a6f1555f0f2e984ffeec51e7a8b9/src/MqttClient.cpp#L380
