### ISSUE TITLE
Compliation error in packet.h

### ISSUE THREAD

**Issue by codePavan** [bertmelis/espMqttClient#23]
Platform IO:

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = bertmelis/espMqttClient@^1.1.1
Hardware : ESP32 Dev Kit V1
Compling Example: simple-esp32

Please find the version and other details in the verbose messages below

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (3.3.2) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.10006.210326 (1.0.6)
 - tool-esptoolpy @ 1.30100.210531 (3.1.0)
 - toolchain-xtensa32 @ 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 29 compatible libraries
Scanning dependencies...
Dependency Graph
|-- espMqttClient @ 1.1.1
|   |-- WiFiClientSecure @ 1.0
|   |   |-- WiFi @ 1.0
|-- Ticker @ 1.1
|-- WiFi @ 1.0
Building in release mode
Compiling .pio\build\esp32doit-devkit-v1\src\main.cpp.o
Archiving .pio\build\esp32doit-devkit-v1\libf43\libWiFi.a
Compiling .pio\build\esp32doit-devkit-v1\lib5a8\WiFiClientSecure\ssl_client.cpp.o
Indexing .pio\build\esp32doit-devkit-v1\libf43\libWiFi.a
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\MqttClient.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\Packets\Packet.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\Packets\Parser.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\Packets\RemainingLength.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\Packets\String.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\espMqttClient.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\lib49f\Ticker\Ticker.cpp.o
Archiving .pio\build\esp32doit-devkit-v1\libFrameworkArduinoVariant.a
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\HardwareSerial.cpp.o
Indexing .pio\build\esp32doit-devkit-v1\libFrameworkArduinoVariant.a
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\IPAddress.cpp.o
Archiving .pio\build\esp32doit-devkit-v1\lib49f\libTicker.a
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\IPv6Address.cpp.o
In file included from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/MqttClient.h:24:0,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/MqttClientSetup.h:14,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/espMqttClient.h:16,
                 from src\main.cpp:4:
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/Packets/Packet.h: In constructor 'espMqttClientInternals::Packet::Packet(espMqttClientTypes::Error&, uint16_t, const char*, uint8_t, const char*, uint8_t, Args&& ...)':   
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/Packets/Packet.h:103:43: error: expected ',' before ')' token
     static_assert(sizeof...(Args) % 2 == 0);
                                           ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src/Packets/Packet.h:103:43: error: expected string-literal before ')' token
Indexing .pio\build\esp32doit-devkit-v1\lib49f\libTicker.a
*** [.pio\build\esp32doit-devkit-v1\src\main.cpp.o] Error 1
In file included from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets\Packet.cpp:9:0:
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets\Packet.h: In constructor 'espMqttClientInternals::Packet::Packet(espMqttClientTypes::Error&, uint16_t, const char*, uint8_t, const char*, uint8_t, Args&& ...)':   
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets\Packet.h:103:43: error: expected ',' before ')' token
     static_assert(sizeof...(Args) % 2 == 0);
                                           ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets\Packet.h:103:43: error: expected string-literal before ')' token
*** [.pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\Packets\Packet.cpp.o] Error 1
In file included from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.h:24:0,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.cpp:9:
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h: In constructor 'espMqttClientInternals::Packet::Packet(espMqttClientTypes::Error&, uint16_t, const char*, uint8_t, const char*, uint8_t, Args&& ...)':   
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h:103:43: error: expected ',' before ')' token
     static_assert(sizeof...(Args) % 2 == 0);
                                           ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h:103:43: error: expected string-literal before ')' token
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.cpp: In member function 'void MqttClient::loop()':
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.cpp:211:7: warning: attributes at the beginning of statement are ignored [-Wattributes]
       [[fallthrough]];
       ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.cpp:213:7: warning: attributes at the beginning of statement are ignored [-Wattributes]
       [[fallthrough]];
       ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.cpp:218:7: warning: attributes at the beginning of statement are ignored [-Wattributes]
       [[fallthrough]];
       ^
*** [.pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\MqttClient.cpp.o] Error 1
In file included from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClient.h:24:0,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\MqttClientSetup.h:14,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\espMqttClient.h:16,
                 from .pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\espMqttClient.cpp:9:
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h: In constructor 'espMqttClientInternals::Packet::Packet(espMqttClientTypes::Error&, uint16_t, const char*, uint8_t, const char*, uint8_t, Args&& ...)':   
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h:103:43: error: expected ',' before ')' token
     static_assert(sizeof...(Args) % 2 == 0);
                                           ^
.pio\libdeps\esp32doit-devkit-v1\espMqttClient\src\Packets/Packet.h:103:43: error: expected string-literal before ')' token
*** [.pio\build\esp32doit-devkit-v1\libd8c\espMqttClient\espMqttClient.cpp.o] Error 1
========================================= [FAILED] Took 5.10 seconds =========================================

 *  The terminal process "C:\Users\pavan\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by bertmelis** [comment]
I'll try to reproduce. Must be something in the build parameters that is different for the various boards.

Also the [[fallthrough]] statement gives a warning.

Are you building with C++11?

**Comment by bertmelis** [comment]
Your Arduino framework version is 1.0.6. Is there a particular reason for not using latest?

**Comment by codePavan** [comment]
There is no particular reason to use older Arduino framework
"cStandard": "c99",
 "cppStandard": "c++11",
are set in the properties

**Comment by bertmelis** [comment]
The latest Arduino framework version uses c++17. If you update you probably won't have the issue anymore.

If you for some reason want to stick to v1.x.x, I have to implement some workarounds. Let me know. If now, please update and try again.

**Comment by bertmelis** [comment]
Updating the Arduino framework solves the issue. If you really need v1.0.6 of the Arduino framework, feel free to reopen the ticket.
