### ISSUE TITLE
Bad file number

### ISSUE THREAD

**Issue by podaen** [bertmelis/espMqttClient#26]
I'm trying you example with my preferences, but it seems not connecting because there is something wrong. Does this sound familiar?

> esp32
> Arduino IDE 1.8.16
> Arduino ESP 2.0.4

> Connecting to MQTT...
> [ 22006][I][Packet.cpp:322] _allocate(): Alloc (l:53)
> [ 22007][V][ssl_client.cpp:62] start_ssl_client(): Free internal heap before TLS 90320
> [ 22009][V][ssl_client.cpp:68] start_ssl_client(): Starting socket
> [ 22060][V][ssl_client.cpp:149] start_ssl_client(): Seeding the random number generator
> [ 22073][V][ssl_client.cpp:158] start_ssl_client(): Setting up the SSL/TLS structure...
> [ 22073][V][ssl_client.cpp:181] start_ssl_client(): Loading CA cert
> [ 22107][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():190]: (-8576) X509 - The CRT/CRL/CSR format is invalid, e.g. different type expected
> [ 22110][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -8576
> [ 22124][V][ssl_client.cpp:324] stop_ssl_socket(): Cleaning SSL connection.
> [ 22124][E][WiFiClient.cpp:313] setSocketOption(): fail on -1, errno: 9, "Bad file number"
> [ 22140][V][ssl_client.cpp:324] stop_ssl_socket(): Cleaning SSL connection.
> [ 22141][I][MqttClient.cpp:627] _clearQueue(): clearing queue (clear session: false)
> Disconnected from MQTT: 0.

**Comment by bertmelis** [comment]
I haven't tried all the TLS features. The lib merely passes the methods from the TCP client to the mqtt client's interface.

Now, the real error is obviously not `bad file number` but `The CRT/CRL/CSR format is invalid, e.g. different type expected`.

How did you specify the certificate?

**Comment by podaen** [comment]
Yes, the error seems familiar. It is well know in the lastest. I think where to look!

**Comment by podaen** [comment]
The certificate is OK now. I accidentally changed something in my code. I didn't expected that.

Still having that bad file number. I don't get it why this setSocketOption() is called.

> Obtained IP address: 192.168.1.135
> Connecting to MQTT...
> [  6385][I][Packet.cpp:322] _allocate(): Alloc (l:53)
> [  6386][I][MqttClient.cpp:263] loop(): Stack usage: 9444/10000
> [  6391][V][ssl_client.cpp:62] start_ssl_client(): Free internal heap before TLS 92660
> [  6399][V][ssl_client.cpp:68] start_ssl_client(): Starting socket
> [  6464][V][ssl_client.cpp:149] start_ssl_client(): Seeding the random number generator
> [  6465][V][ssl_client.cpp:158] start_ssl_client(): Setting up the SSL/TLS structure...
> [  6470][V][ssl_client.cpp:181] start_ssl_client(): Loading CA cert
> [  6480][V][ssl_client.cpp:257] start_ssl_client(): Setting hostname for TLS session...
> [  6483][V][ssl_client.cpp:272] start_ssl_client(): Performing the SSL/TLS handshake...
> [  9324][V][ssl_client.cpp:293] start_ssl_client(): Verifying peer X.509 certificate...
> [  9325][V][ssl_client.cpp:301] start_ssl_client(): Certificate verified.
> [  9337][V][ssl_client.cpp:316] start_ssl_client(): Free internal heap after TLS 47540
> [  9337][E][WiFiClient.cpp:313] setSocketOption(): fail on -1, errno: 9, "Bad file number"
> [  9355][I][MqttClient.cpp:263] loop(): Stack usage: 6964/10000
> [  9355][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 53 bytes...
> [  9358][I][MqttClient.cpp:309] _checkOutgoing(): tx 53/53
> Guru Meditation Error: Core  1 panic'ed (Double exception). 

> Exception:Error:
> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/xtensa_context.S:195:::0x40095c62:_xt_context_save
> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/xtensa_vectors.S:1820:::0x40080080:_WindowOverflow8
> /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/machine/xtensa/strlen.S:84:::0x40092f39:strlen
> /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/machine/xtensa/strlen.S:96:::0x40092f49:strlen
> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/xtensa_context.S:194:::0x40095c5f:_xt_context_save
> G:\Documents\Visual Studio 2019\Arduino\libraries\espMqttClient\src\Transport/ClientSecureSync.cpp(39): error 0x40221279:espMqttClientInternals
> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/xtensa_vectors.S:1799:::0x4008007d:_xt_alloca_exc
> 0x40078000: ?? ??:0
> ??:?:::0x40080400:_init
> 0x400805f0: ?? ??:0

It's crashing because it didn't had a proper socket to read I think.

**Comment by bertmelis** [comment]
No, that is a bug in the WiFiClientSecure library. It doesn't do any harm though. It's just trying to set an option.

There is a bug in my code. I fixed it in the main branch. Will publish a bugfix release later today.

See https://github.com/bertmelis/espMqttClient/commit/9cba9bcc5a4e2d90aedccc3b1c3637772eaadf1a

**Comment by podaen** [comment]
It can wait. No problem!

**Comment by bertmelis** [comment]
https://github.com/bertmelis/espMqttClient/releases/tag/v1.2.2

**Comment by podaen** [comment]
It's connected now! I don't see the setSocketOption() anymore. Seems to be solved too.

To login to server I needed to add this line to the onConnect()... You will probably know.

```
Serial.print("Client ID: ");
Serial.println(mqttClient.getClientId());
```

I only initialized these.

	mqttClient.setCACert(root_ca);
	mqttClient.setCredentials(MQTT_USER, MQTT_PASS);
	mqttClient.onConnect(onMqttConnect);
	mqttClient.onDisconnect(onMqttDisconnect);
	//mqttClient.onSubscribe(onMqttSubscribe);
	//mqttClient.onUnsubscribe(onMqttUnsubscribe);
	//mqttClient.onMessage(onMqttMessage);
	//mqttClient.onPublish(onMqttPublish);
	mqttClient.setServer(MQTT_HOST, MQTT_PORT);
	mqttClient.setCleanSession(true);

And it seems it is checking for messages

> [  9715][I][MqttClient.cpp:383] _checkIncoming(): Parsed 4 - remaining 0
> [ 24607][I][MqttClient.cpp:405] _checkPing(): Near keepalive, sending PING
> [ 24608][I][Packet.cpp:322] _allocate(): Alloc (l:2)
> [ 24609][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 2 bytes...
> [ 24625][I][MqttClient.cpp:309] _checkOutgoing(): tx 2/2
> [ 24676][I][MqttClient.cpp:331] _checkIncoming(): rx len 2
> [ 24676][I][Parser.cpp:111] _fixedHeader(): Packet type: 0xd0
> [ 24676][I][Parser.cpp:174] _remainingLengthNone(): Remaining length: 0

Can I turn it off?

**Comment by bertmelis** [comment]
> Can I turn it off?

Turn off what? The debug messages? That's a compile time option. Are you using Arduino IDE or Platformio?

**Comment by bertmelis** [comment]
You always need to check for messages. You need to check if the server is responding.

You can safely disable the onConnect callback if you don't need it and use connected() to check if the client is connected. Mind though there is no automatic reconnect logic. You have to do that in your code.

**Comment by bertmelis** [comment]
Ok.

Closing as it seems solved with the latest release.

Feel free to reopen or create a new issue if it doesn't work.

**Comment by podaen** [comment]
The socketoption is back, but it is connecting...

> Connecting to MQTT...
> [  6516][I][Packet.cpp:322] _allocate(): Alloc (l:53)
> [  6517][I][MqttClient.cpp:263] loop(): Stack usage: 9444/10000
> [  6522][V][ssl_client.cpp:62] start_ssl_client(): Free internal heap before TLS 92532
> [  6530][V][ssl_client.cpp:68] start_ssl_client(): Starting socket
> [  6608][V][ssl_client.cpp:149] start_ssl_client(): Seeding the random number generator
> [  6620][V][ssl_client.cpp:158] start_ssl_client(): Setting up the SSL/TLS structure...
> [  6636][V][ssl_client.cpp:181] start_ssl_client(): Loading CA cert
> [  6657][V][ssl_client.cpp:257] start_ssl_client(): Setting hostname for TLS session...
> [  6658][V][ssl_client.cpp:272] start_ssl_client(): Performing the SSL/TLS handshake...
> [  9919][V][ssl_client.cpp:293] start_ssl_client(): Verifying peer X.509 certificate...
> [  9920][V][ssl_client.cpp:301] start_ssl_client(): Certificate verified.
> [  9923][V][ssl_client.cpp:316] start_ssl_client(): Free internal heap after TLS 47524
> [  9934][E][WiFiClient.cpp:313] setSocketOption(): fail on -1, errno: 9, "Bad file number"
> [  9939][I][MqttClient.cpp:263] loop(): Stack usage: 6964/10000
> [  9951][V][ssl_client.cpp:369] send_ssl_data(): Writing HTTP request with 53 bytes...
> [  9953][I][MqttClient.cpp:309] _checkOutgoing(): tx 53/53
> [ 10071][I][MqttClient.cpp:331] _checkIncoming(): rx len 4
> [ 10072][I][Parser.cpp:111] _fixedHeader(): Packet type: 0x20
> [ 10072][I][Parser.cpp:124] _remainingLengthFixed(): Remaining length: 2
> [ 10087][I][Parser.cpp:198] _varHeaderConnack2(): Packet complete
> [ 10087][I][MqttClient.cpp:627] _clearQueue(): clearing queue (clear session: true)
> Connected to MQTT.

Don't know why, but when I login to the Websockets Client on the webpage it connects for 5sec to the client and then disconnect. When I connect again, it does the same thing again. That's new for me (the ping too)... Any idea's? The connection doesn't seems lost on the esp. I read a note in the documentation of the MQTT...

> "KeepAlive"
> Q: What does a PING message look like? Does the KeepAlive timer get reset when data is sent/received? Is the ping sent just when the KeepAlive time is about to be lapsed?
> 
> As long as messages are exchanged frequently and the keep-alive interval is not exceeded, there is no need to send an extra message to establish whether the connection is still open. As and when the client sends PINGREQ/PUBLISH/SUBSRIBE packets to the broker the keepAlive timer gets reset.

Do I need to modify this somewhere on my esp "PINGREQ/PUBLISH/SUBSRIBE"?

**Comment by bertmelis** [comment]
Read my previous comment on the "bad file number". It doesn't influence this lib.

I cannot help with your websocket client. That is not my work, please ask the maintainer of that lib.

You cannot change the behaviour of the ping/pong mechanism. It's part of the MQTT specification to ensure both client and server are sure the other end is still connected.

**Comment by podaen** [comment]
Your right, it doesn't. 

> Don't know why, but when I login to the Websockets Client on the webpage it connects for 5sec to the client and then disconnect. When I connect again, it does the same thing again. That's new for me (the ping too)... Any idea's? The connection doesn't seems lost on the esp. I read a note in the documentation of the MQTT...

I choose the same clientID for the webviewer... I forgot. That was why it disconnected. It's running fine now.

You can place HiveMQ on your checklist! Thanks for helping me out.

**Comment by bertmelis** [comment]
Super!
