### ISSUE TITLE
Turn off WiFi

### ISSUE THREAD

**Issue by podaen** [bertmelis/espMqttClient#28]
esp32 
Arduino IDE 1.8.16
Arduino ESP 2.0.4

No bug, request for a feature.

Can you add some function in the class to remove the MQTT please, like I do for the WiFi network? 

> void DeIniWifi() {
> 	WiFi.removeEvent(WiFiEvent);
> 	WiFi.disconnect(true);
> }

**Comment by bertmelis** [comment]
What do you mean with remove? You can just disconnect, which is already possible.
