### ISSUE TITLE
Slow when there is no payload

### ISSUE THREAD

**Issue by podaen** [bertmelis/espMqttClient#36]
When sending a payload in a message it react significantly faster when there is not.

**Comment by bertmelis** [comment]
Async or sync? TLS or non secure?

**Comment by podaen** [comment]
Async TLS

**Comment by bertmelis** [comment]
I will not test myself for async TLS. There are multiple forks of the original (ESP)AsyncTCP library which implement TLS with or without additional bugfixes. It's up to you to decide which one to use.

I've created a possible bugfix though, in PR #37, that will improve responsiveness for async and syncsecure.

**Comment by podaen** [comment]
Still slow. Do I need to define anything in my code?

**Comment by podaen** [comment]
I can easily solve it by just sending a random number...

**Comment by bertmelis** [comment]
Well, it's strange because there is no difference in how the lib handles empty payloads. So I thought it would be that the TCP packet was below a certain threshold to activate the Nagle algorithm.

So if fixing Nagle doesn't help, I really don't know where to look.

How do you measure?

**Comment by podaen** [comment]
I'm actually doesn't understand it eater. Sometimes it comes in faster. But It's clear it has something to do with no payload. I think it's because the lower task priority. In my log I see it's checking every 10sec on packages. But when there is payload it comes in eminently, so it's maybe an other reason why it doesn't come in that fast. Finding that problem could take a lot of time I don't have now. It's only two bytes. So I'm not losing a lot of memory. Thanks for looking in to it!

**Comment by bertmelis** [comment]
You are talking about sending packages with no payload using the ESP, right?
Or receiving on the ESP?

**Comment by bertmelis** [comment]
There might be an issue with the parser when receiving empty payloads.

**Comment by bertmelis** [comment]
@podaen This fix should do it.

**Comment by bertmelis** [comment]
Will be fixed in next release. Until then, you can use the git version.

**Comment by bertmelis** [comment]
Darn. I forgot something. Will fix in an hour.

**Comment by bertmelis** [comment]
Fixed with https://github.com/bertmelis/espMqttClient/commit/6691a6216a49dcb7c43cda76e1f1d3e3b533c6ff

**Comment by podaen** [comment]
Yup, everything works just fine now. So this issue can be closed.

**Comment by podaen** [comment]
Speak to fast. my stream starts to run slow.

**Comment by podaen** [comment]
It doesn't have problems when there is no other stream running after the msg is received with no payload. So I think something keep busy for a few seconds.

**Comment by bertmelis** [comment]
Sorry, can you explain again what happens?
You're receiving qos0 publish packets without payload. When exactly does it choke?

**Comment by podaen** [comment]
After receiving an empty payload, my stream (not this lib) start collecting data (http) and it start to slowdown for a few seconds and than it recovers.

I don't know man what it is. It seems that my two clients (stream and mqtt) having an conflict. So my stream reconnects to the host and the MQTT reconnects.

[126468][W][MqttClient.cpp:404] _checkPing(): Disconnecting, server exceeded keepalive

After that evrything works again.

> You're receiving qos0 publish packets without payload.

I don't see that in my log.

**Comment by podaen** [comment]
if you organize your log more, I can give you more info.

**Comment by podaen** [comment]
I was thinking... I don't see everything in the log because, I see in the log it is checking on packages every +-10seconds, but when a packages comes in it react immediately, it reminds me now that it is probably a callback. It starts from there... You did already the NULL parsing, but maybe my app doesn't send a NULL. I am just guessing. Did you do something like this?

```
	char* chr = NULL;
	if (constChrSize(src) == 0) {
		printf("arg src.length is 0, return.");
		return chr;
	}
```

**Comment by bertmelis** [comment]
Can I ask you, which async library do you use for Async/TLS?

The (standard) underlying async library uses callbacks and they are called (1) on receipt of any data and (2) every 500msec. So at least every 500msecs the incoming and outgoing data is processed, if there is any. Also ping is checked. When fully connected, this subroutines is called:
https://github.com/bertmelis/espMqttClient/blob/main/src/MqttClient.cpp#L238

The parser doesn't care about the contents of the payload. It calculates the payload length: tot total message length - topic length - packetID length. Should your application send a NULL-character, the payload length isn't 0 but 1.

For zero-length payloads, the payload length check is here:
https://github.com/bertmelis/espMqttClient/blob/main/src/Packets/Parser.cpp#L228
and here:
https://github.com/bertmelis/espMqttClient/blob/main/src/Packets/Parser.cpp#L276

If there is a payload, the parser jumps to here:
https://github.com/bertmelis/espMqttClient/blob/main/src/Packets/Parser.cpp#L304

**Comment by podaen** [comment]
> Can I ask you, which async library do you use for Async/TLS?

I am using this one [AsyncTCP](https://github.com/me-no-dev/AsyncTCP/)...

**Comment by bertmelis** [comment]
Surely you use one of the forks (or PRs) because out of the box it doesn't support TLS.

**Comment by podaen** [comment]
what are you suggesting... leaving the TLS out? I think I can log in without TLS over the same port only by using user and pass. So my setup will look like this?

```
	Serial.print("getFreeHeap: ");
	Serial.println(ESP.getFreeHeap());
	mqttClient.setInsecure();
	//mqttClient.setCACert(root_ca);
	mqttClient.setCredentials(MQTT_USER, MQTT_PASS);
	Serial.print("getFreeHeap: ");
	Serial.println(ESP.getFreeHeap());
	mqttClient.onConnect(onMqttConnect);
	mqttClient.onDisconnect(onMqttDisconnect);
	//mqttClient.onSubscribe(onMqttSubscribe);
	//mqttClient.onUnsubscribe(onMqttUnsubscribe);
	mqttClient.onMessage(onMqttMessage);
	//mqttClient.onPublish(onMqttPublish);
	mqttClient.setServer(MQTT_HOST, MQTT_PORT);
	Serial.print("getFreeHeap: ");
	Serial.println(ESP.getFreeHeap());
	mqttClient.setCleanSession(true);
```

**Comment by bertmelis** [comment]
You don't need to skip TLS. It's only that on ESP32 using the Async version there is no TLS when you use the original library. It just doesn't work. And even if there was, I don't think espMqttClient would compile without modifications (same goes for ESP8266).

My thoughts are you are using the "regular" sync version, which is non-blocking so from your code's point of view there is not much difference.
You're using `setInsecure()` which is part of the sync version and is not available in the async version.

It doesn't matter for the problem though.

Just to be sure: you are using an ESP32 board, right?

**Comment by bertmelis** [comment]
(I guess you're using the sync version.)

`setInsecure` is still TLS. It just doesn't check the validity of the certificate. The TCP stream is still encrypted though. From MQTT point of view, there is absolutely no difference in behaviour between TLS, unsecured or TLS-insecure. TCP takes care of this and delivers the decrypted TCP payload to the MQTT client.

Since you're using the sync version, the speed at which the client reacts depends on the priority of the MQTT task. The task polls the TCP client for incoming data and if there is any, it starts parsing. With the latest fix (in git, not yet in release) it should also act immediately on empty payloads.

I've added testing for receiving packets with and without payload. There is no lag noticeable during testing. I'm going to close the issue again. But don't let this hold you back from discussing the issue further!

**Comment by podaen** [comment]
Now I understand. It became clear when I read the read me. Now I can answer your question "am I using sync or async?".

The espMqttClientSecure and the espMqttClient mqttClient; are sync. The espMqttClientAsync is for an async client. That been know. Yes I am using the non blocking (sync).

Then there is still a bug in it. Because this below still happens.

> After receiving an empty payload, my stream (not this lib) start collecting data (http) and it start to slowdown for a few seconds and than it recovers.

> I don't know man what it is. It seems that my two clients (stream and mqtt) having an conflict. So my stream reconnects to the host and the MQTT reconnects.

Now I also know it only occurs with a CA and not for insecure TSL.

**Comment by bertmelis** [comment]
Connecting using a secure connection takes a few seconds. It involves some calculation.

You're sure it's not the https process that blocks?
There is no blocking/delay (anymore) in the CI-tests that I run on the mqtt client.

**Comment by bertmelis** [comment]
Since you're using an esp32, you can offload the http process to a separate task and use (eg) semaphores to  flag the task to run.

**Comment by podaen** [comment]
> You're sure it's not the https process that blocks?

Probably... the MQTT was already connected and as well the MQTT (https) and the stream (http) disconnects because of a timeout. So it is higher in the hierarchy. Maybe the Arduino component has some troubles to handle this.

> Since you're using an esp32, you can offload the http process to a separate task and use (eg) semaphores to flag the task to run.

It will be less work by just sending a random number in case of using a certificate. But thanks for the advice. I think we are done now.
