### ISSUE TITLE
Disconnection description 

### ISSUE THREAD

**Issue by podaen** [bertmelis/espMqttClient#42]
Maybe an idea for you is to define the reason of disconnection like this info.wifi_sta_disconnected.reason do, so description of disconnect is shown. The info is WiFiEventInfo_t, take a look... you will see.

**Comment by podaen** [comment]
my mistake, it's the same. Don't know where I saw it then...

**Comment by podaen** [comment]
It is a switch case with the reason number `onMqttDisconnect`. I will do!

**Comment by bertmelis** [comment]
It's here: https://github.com/bertmelis/espMqttClient/blob/main/src/TypeDefs.h#L18

You cannot "print" the reasons though.

**Comment by podaen** [comment]
I just tried

```
	switch (reason) {
	case USER_OK:
		Serial.println("MQTT user ok");
		break;
```
`USER_OK` is undefined...

**Comment by bertmelis** [comment]
I can implement this in the lib:
```cpp
static const char* disconnectReasonToString(DisconnectReason error) {
  switch (error) {
    case USER_OK:                            return "No error";
    case MQTT_UNACCEPTABLE_PROTOCOL_VERSION: return "Unacceptable protocol version";
    case MQTT_IDENTIFIER_REJECTED:           return "Identified rejected";
    case MQTT_SERVER_UNAVAILABLE:            return "Server unavailable";
    case MQTT_MALFORMED_CREDENTIALS:         return "Malformed credentials";
    case MQTT_NOT_AUTHORIZED:                return "Not authorized";
    case TLS_BAD_FINGERPRINT:                return "Bad fingerprint";
    case TCP_DISCONNECTED:                   return "TCP disconnected";
}
```

If you want to do it in your code, you need to prepend the enum with the namespace:

```cpp
	switch (reason) {
	case espMqttClientTypes::DisconnectReason::USER_OK:
		Serial.println("MQTT user ok");
		break;
```

**Comment by podaen** [comment]
> If you want to do it in your code, you need to prepend the enum with the namespace:

Yes, it works. Thanks!

**Comment by podaen** [comment]
It would be better to register the events. This is using FreeRTOS.

#include "esp_event.h"

Before initializing... 

`s_wifi_event_group = xEventGroupCreate();`

this after the mqtt is initialized 

```
  esp_event_handler_instance_t instance_any_id;
    esp_event_handler_instance_t instance_got_ip;

    err = esp_event_handler_instance_register(WIFI_EVENT,
        ESP_EVENT_ANY_ID,
        &event_handler,
        NULL,
        &instance_any_id);
    if (err != ESP_OK) {
        Serial.println(err);
        Serial.println("Could not set ESP_EVENT_ANY_ID");
        return false;
    }
    err = esp_event_handler_instance_register(IP_EVENT,
        IP_EVENT_STA_GOT_IP,
        &event_handler,
        NULL,
        &instance_got_ip);
    if (err != ESP_OK) {
        Serial.println(err);
        Serial.println("Could not set IP_EVENT_STA_GOT_IP");
        return false;
    }
```

They can also be unregistered like this.

```
    err = esp_event_handler_unregister(IP_EVENT, IP_EVENT_STA_GOT_IP, &event_handler);
    if (err != ESP_OK) {
        Serial.println(err);
        Serial.println("Could not unregister IP_EVENT_STA_GOT_IP!");
        return false;
    }
    err = esp_event_handler_unregister(WIFI_EVENT, ESP_EVENT_ANY_ID, &event_handler);
    if (err != ESP_OK) {
        Serial.println(err);
        Serial.println("Could not unregister ESP_EVENT_ANY_ID!");
        return false;
    }
    vEventGroupDelete(s_wifi_event_group);
```

**Comment by bertmelis** [comment]
Esp8266 has no FreeRTOS. And I try to keep the API close to asyncmqttclient.

So this is no option.

**Comment by podaen** [comment]
Esp8266 is getting old... Is replaced by ESP8684 (C2) that supports FreeRTOS.

**Comment by Pablo2048** [comment]
It make no sense if it's getting old or not. This library claims that is compatible with the ESP8266 so it should be...

**Comment by bertmelis** [comment]
Electronic equipment is becoming obsolete faster and faster nowadays but I try not to follow this trend. I have several esp8266 devices in use myself and no plans for a de facto useless upgrade.
