### ISSUE TITLE
import lib

### ISSUE THREAD

**Issue by podaen** [bertmelis/espMqttClient#47]
I looked in to the library.properties file and I see there is no top header file reference `includes=*.h` for importing libs.

**Comment by bertmelis** [comment]
Because it's an optional property. Does it break something?

**Comment by bertmelis** [comment]
Unless it has a clear advantage to include this, this is not an issue.

**Comment by podaen** [comment]
The problems got away, but still it's not a best way to make a library for arduino. Better to make a a header file where you redirect to the things you need with if defined in a config file (for including perpeces) and that choise what you class you want to use.
