### ISSUE TITLE
qos1 does not publish when not connected to wifi?

### ISSUE THREAD

**Issue by Bernard314** [bertmelis/espMqttClient#59]
I wanted to use qos1 messages to make sure messages from my esp32 reach aws cloud because the wifi in my factory is very unreliable. I was testing to see if messages that were supposed to be sent when the wifi is off are sent when the esp32 reconnects to wifi however this is not the case. am i missing something?

**Comment by bertmelis** [comment]
They should be enqueued and sent as soon as the connection is established again.

Now, I see in the code that when a client connects with cleansession == true, outgoing queued publish messages are deleted on connect. This is not what is expected.
Do you connect with clean session == true? (mind that even when cleansession == false, the broker can still connack with clean session == true)

**Comment by Bernard314** [comment]
yes. what should i do to prevent this?

**Comment by bertmelis** [comment]
you cannot. It's a business logic error in the code. I'll publish a fix in a minute.

**Comment by bertmelis** [comment]
Sorry, you can connect with cleansession == false. Then outgoing publish messages with qos > 0 will be preserved. But the broker has to confirm the session. So it's not 100% failsafe.

**Comment by Bernard314** [comment]
yeah i tried it works. 

> But the broker has to confirm the session
sorry what does this mean?

**Comment by bertmelis** [comment]
> > But the broker has to confirm the session

> sorry what does this mean?

The client stores session data but so does the broker. If you connect with cleansession set to false but the broker doesn't have a session stored for your client, it cannot confirm and will CONNACK with session false.

For example: you reboot the broker and all stored data is lost on reboot. The client will reconnect assuming the broker still has a session stored.

**Comment by bertmelis** [comment]
Business logic has been changed in PR #60 .

You can test with branch `keep-PUB-on-cleansession`. I give myself some time before merging to think this over.

**Comment by bertmelis** [comment]
Thinking about this. I'm deleting QoS0 messages on connect now but we maybe should keep them too.

This would enable an efficient publish/connect/disconnect/sleep cycle.

Adjusted the code accordingly.
