### ISSUE TITLE
Control logging via DEBUG_ESP_MQTT_CLIENT for ESP32

### ISSUE THREAD

**Issue by technyon** [bertmelis/espMqttClient#63]
Hi,

I've seen that in Logging.h, the symbol DEBUG_ESP_MQTT_CLIENT can enable or disable logging for the ESP8266, but not for the ESP32. Is there any reason that? Otherwise I'd add it and open a PR.

**Comment by bertmelis** [comment]
Both platforms have a different way of enabling debug output on Serial. I merely tried to "extend" this.

I'm open for improvements, I don't have an opinion about this.

**Comment by technyon** [comment]
ok ... maybe I misunderstood something. I'd do it like this:

```
#if defined(ARDUINO_ARCH_ESP32)
  // Logging is en/disabled by Arduino framework macros
  #include <esp32-hal-log.h>
  #if defined(DEBUG_ESP_MQTT_CLIENT)
    #define emc_log_i(...) log_i(__VA_ARGS__)
    #define emc_log_e(...) log_e(__VA_ARGS__)
    #define emc_log_w(...) log_w(__VA_ARGS__)
  #else
    #define emc_log_i(...)
    #define emc_log_e(...)
    #define emc_log_w(...)
  #endif
#elif defined(ARDUINO_ARCH_ESP8266)
...
```

**Comment by bertmelis** [comment]
Sure.

Debugging will still need to be enabled in the Arduino framework. I suppose that is your intent.

**Comment by technyon** [comment]
Yes, but on top of that I want per-library control. If I debug bluetooth-related issues for example, it's not helpful to have the mqtt messages logged and makes the logs a lot harder to read. I've put this into my fork already, I can create a PR if it's ok for you.

**Comment by bertmelis** [comment]
You're right about that! Please, a PR is welcome.

**Comment by technyon** [comment]
PR created
