### ISSUE TITLE
[SOLVED] Compile error with ESP32

### ISSUE THREAD

**Issue by sude22** [bertmelis/espMqttClient#66]
Hello Bert,
Long time no see. 
I was happy to see your MQTT library (V1.1.3). 
But when I try to compile a simple project for the ESP32 I get the following error: 

`
Compiling .pio\build\wemos_d1_mini32\libf63\espMqttClient\espMqttClient.cpp.o
.pio/libdeps/wemos_d1_mini32/espMqttClient/src/Transport/ClientSync.cpp: In member function 'virtual bool espMqttClientInternals::ClientSync::connect(IPAddress, uint16_t)':
.pio/libdeps/wemos_d1_mini32/espMqttClient/src/Transport/ClientSync.cpp:29:71: error: no matching function for call 
to 'WiFiClient::setSocketOption(int, int, int*, unsigned int)'
     client.setSocketOption(IPPROTO_TCP, TCP_NODELAY, &val, sizeof(int));
`
Do you have a hint for me?
Greetings, Siggi

**Comment by bertmelis** [comment]
> My biggest hope is that with your library the reconnect problems of the AsycMqttClient library disappear ;)

Finger crossed. It's not incorporated in the examples, but the connect-function has a return value. You should not ignore this when (re)connecting.

**Comment by sude22** [comment]
Could you please give an example how you do the reconnecting?

**Comment by sude22** [comment]
Hi Bert,
thank you for the provided examples regarding the reconnect.
I have some tests running with your lib, right now it seems to be rock stable! ;)
But I have not tested the reconnection issue due to lack of time, but I will.
In the past, with Homie, the problem occurs only when the MQTT-Broker was gone while WiFi was still present....

**Comment by bertmelis** [comment]
> In the past, with Homie, the problem occurs only when the MQTT-Broker was gone while WiFi was still present....

MQTT's keepalive should still trigger a disconnect.
I don't give any guarantees this lib will never fail. It is hard to test every possible scenario. Only userdata will tell.
