### ISSUE TITLE
[BUG] Warning while resolving dependencies

### ISSUE THREAD

**Issue by sude22** [bertmelis/espMqttClient#79]
Hi Bert,

I noticed that there is a warning:
`
Resolving wemos_d1_mini32 dependencies...
Library Manager: Installing bertmelis/espMqttClient @ ^1.4.0
Unpacking
Library Manager: espMqttClient@1.4.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing AsyncTCP @ >=1.1.1
Library Manager: Warning! More than one package has been found by AsyncTCP @ >=1.1.1 requirements:
Library Manager:  - me-no-dev/AsyncTCP@1.1.1
Library Manager:  - kubafilinger/AsyncTCP@1.1.1
Library Manager:  - zeed/AsyncTCP@1.1.1
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (shown above) to avoid name conflicts
Unpacking
Library Manager: AsyncTCP@1.1.1 has been installed!
`

This may not be a real bug, but I wanted to at least point it out.

**Comment by bertmelis** [comment]
When registering a package in the platformio registry, you get a warning when you are registering a library with an existing name. This is what happens if you ignore this warning.

I'll update the requirements with the package owner. I'm not going to create a new release for this fix though.

**Comment by bertmelis** [comment]
Solved in https://github.com/bertmelis/espMqttClient/commit/eea0d3df43946c99f9788e049480eca123e61bdd

I suppose this is only a warning and not a showstopping error.
