### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fabltd** [bertmelis/espMqttClient#99]
ESP32

When publishing. I am seeing the published message printed in the console. How to disable this?

**Comment by bertmelis** [comment]
Please provide a code snippet.

But even then, there is no such code in this library. Even de debug statements don't print the message to uart.

**Comment by fabltd** [comment]
Hi 

I found a debug statement in my own code and fixed that. I have a different issue now.

I use this lib to indicate state.

`https://github.com/jandelgado/jled/tree/master#blinking-example`

It works without your MQTT lib but with it this does not work. Is there some kind of timing conflict?

By the way this is the only MQTT lib I have found that is reliable and seems to be active. Nice work

**Comment by bertmelis** [comment]
Are you using the latest release or are you using latest git version?

I suspect some timing issues as I also had some troubles getting task priorities and timings right on one of my personal projects. The latest git version should improve this.

**Comment by fabltd** [comment]
Thanks for reaching out. I updated to the latest version. I then switched to the esp32 tick libiary and now its working. I am sure its a timing issue but didn't have enough time to keep trying.

**Comment by bertmelis** [comment]
Closing because it seems to be solved.

Feel free to reopen if not.
